version: '3.8'
services:
  postgres:
    container_name: postgres-pictures
    image: 'postgres:15.5'
    restart: always
    environment:
      - 'POSTGRES_DB=nasa_pictures'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - "5433:5432"
